package rules
 
import com.example.demo.Product
import java.util.Date
import function com.example.demo.ProductService.calculateMax;

function String printHello(String name){
	System.out.println("Executing function printHello");
	return "Hello " + name;
}

declare Person
  name : String
  dateOfBirth : Date
end

global java.util.List myGlobalList;

rule "Using a global"
  when
    // Empty
  then
    myGlobalList.add( "My global list" );
end
rule "Offer for Diamond"
	when 
		productObject: Product(type=="diamond")
	then
		productObject.setDiscount(15);
		productObject.setMessage(printHello("Diamond product"));
		System.out.println("Maximum is" + calculateMax(12,13));
end
rule "Offer for Gold"
	when 
		productObject: Product(type=="gold")
	then
		productObject.setDiscount(25);
	end
rule "Using a declared type"
  when
    p : Person( name == "James" )
  then   
    Person mark = new Person();
    mark.setName( "Mark" );
    System.out.println("Person is James");
    insert( mark );
end